sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t alamwasim/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true alamwasim/docker-react npm run test